theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
title: Connie's Blog
description: Welcome to my page! This site will showcase the various coding and analytics projects I have done in the past.
